services:
  - type: web
    name: incident-tracker-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    dir: backend

  - type: web
    name: incident-tracker-frontend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: NODE_ENV
        value: production
    dir: frontend
